profile:
  property:
    value: This the the application.yaml file

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

#db:
#  jdbc:
#    url: jdbc:postgresql://127.0.0.1:5432/accidents
#    username: postgres
#    password: password
#    driver: org.postgresql.Driver

#hibernate:
#  dialect: org.hibernate.dialect.PostgreSQLDialect



spring:
  profiles.active: jpa

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/accidents
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties.hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false